

void UPDATE_CAN_DATA(void){

// WE WILL COLLECT THE DATA FROM FROM A " MCP2515 "  CAN BUS MODULE 
// WE WILL INTERACT THE MODULE VIA SPI INTERFACE 
//    THE CORRESPONDING CODE NEED TO UPDATE     WILL UPDATE SOON


  
}
